name: Deploy to Azure using Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push Docker image
    - name: Build and push Docker image to Docker Hub
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-django-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/my-django-app:latest

   # Deploy to Azure Virtual Machine
    - name: Deploy to Azure VM
      run: |
        # SSH into the VM and deploy the application
        sshpass -p "${{ secrets.VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} << EOF
            # Pull the latest Docker image from the registry
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-django-app:latest
            
            # Stop the existing container (if running)
            docker stop my-django-app || true
            docker rm my-django-app || true

            # Start a new container with the updated image
            docker run -d \
            --name my-django-app \
            -p 80:80 \
            ${{ secrets.DOCKER_USERNAME }}/my-django-app:latest
        EOF

